# Generated by Django 3.2.16 on 2022-11-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Senha', models.CharField(max_length=100)),
                ('Unidade_Temperatura', models.CharField(max_length=1)),
                ('token', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
