# Generated by Django 3.2.16 on 2022-11-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Senha', models.CharField(max_length=100)),
                ('Unidade_Temperatura', models.CharField(max_length=1)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias_Paises',
            fields=[
                ('ID_Cadastro', models.AutoField(primary_key=True, serialize=False)),
                ('cod_pais', models.CharField(max_length=10)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Preferenciais_Tempo',
            fields=[
                ('ID_Cadastro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tempo', models.CharField(max_length=50)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cadastro')),
            ],
        ),
    ]
