# Generated by Django 3.2.16 on 2022-11-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221106_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferenciais_tempo',
            old_name='tipo_templo',
            new_name='tipo_tempo',
        ),
    ]
