# Generated by Django 3.2.16 on 2022-11-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tipo_templo_preferenciais_tempo_tipo_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
