# Generated by Django 3.2.8 on 2022-11-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHoliday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Usuario_Clima_Prefenrencia',
            field=models.ManyToManyField(to='GreatHoliday.Preferencias_Clima'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_Nome_Pais',
            field=models.ManyToManyField(to='GreatHoliday.Preferencias_Paises'),
        ),
    ]
